name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt
    - run: pip install pytest aioresponses mypy black flake8
    - run: black --check .
    - run: flake8 .
    - run: mypy app/
    - run: pytest -q 