- name: tass_defense
  rss: https://tass.ru/rss/v2.xml?themes=155
- name: ria_defense
  rss: https://ria.ru/export/rss2/topic/defense/index.xml
- name: milru
  rss: https://function.mil.ru/rss
- name: rostech
  rss: https://rostech.ru/news/?format=rss
- name: kommersant_oborona
  rss: https://www.kommersant.ru/RSS/section/92
- name: rg_rus_arm
  rss: https://rg.ru/theme/rss/rosorujie.xml
- name: d_russia_goz
  rss: https://d-russia.ru/category/gosoboronzakaz/feed
- name: bmpd_blog
  rss: https://bmpd.livejournal.com/data/rss 
# --- ГОС-IT / цифровизация ---
- name: minfin_gis
  rss: https://digital.gov.ru/ru/events/rss

# --- НИОКР / наука ---
- name: rosciencia_defense
  rss: https://scientificrussia.ru/rss/theme/oborona.xml

# --- экспорт вооружений / ВТС ---
- name: rostec_vtc
  rss: https://rostech.ru/news/tags/vtc/?format=rss

# --- региональные заводы / корпорации ---
- name: uvz_news
  rss: https://www.uvz.ru/rss/news

# --- законы/ФОИВ ---
- name: duma_defense_bills
  rss: https://sozd.duma.gov.ru/rss/43?search=оборон 